# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  #
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
    
      - name: Restore Occlusions libraries
        run: 
          dotnet restore "${{ github.workspace }}\Occlusion Voice Chat_CrossPlatform\Occlusion Voice Chat_CrossPlatform.csproj" -r linux-x64
          
      - name: Publish Occlusion to a folder
        run: 
          dotnet publish "${{ github.workspace }}\Occlusion Voice Chat_CrossPlatform\Occlusion Voice Chat_CrossPlatform.csproj" -c "Release" -r linux-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true --output "occlusionlinuxrelease/"

      - name: Copy Libraries
        run:
          cp "${{ github.workspace }}/Occlusion Voice Chat_CrossPlatform/linuxdeblibs/SDL2.so" "${{ github.workspace }}/occlusionlinuxrelease/SDL2.so";
          cp "${{ github.workspace }}/Occlusion Voice Chat_CrossPlatform/linuxdeblibs/SDL2.a" "${{ github.workspace }}/occlusionlinuxrelease/SDL2.a";
          cp "${{ github.workspace }}/Occlusion Voice Chat_CrossPlatform/linuxdeblibs/opus.so" "${{ github.workspace }}/occlusionlinuxrelease/opus.so"
          
      - name: Zip the published binaries.
        uses: master-atul/tar-action@v1.1.0
        with:
          command: c
          cwd: '${{ github.workspace }}/'
          files: |
            ./occlusionlinuxrelease/
          outPath: occlusion-linux-x64-binaries.tar.gz
          
      - name: And upload an artifact.
        uses: actions/upload-artifact@v2
        with:
          name: occlusion-linux-x64-binaries-artifact
          path: occlusion-linux-x64-binaries.tar.gz


  build-mac:
    # Mac OS 10.15 Catalina
    runs-on: macos-10.15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore Occlusions libraries
        run: 
          dotnet restore "${{ github.workspace }}\Occlusion Voice Chat_CrossPlatform\Occlusion Voice Chat_CrossPlatform.csproj" -r osx-x64

      - name: Publish Occlusion to a folder.
        run: 
          dotnet msbuild "${{ github.workspace }}\Occlusion Voice Chat_CrossPlatform\Occlusion Voice Chat_CrossPlatform.csproj" -t:BundleApp -p:UseAppHost=true -p:RuntimeIdentifier=osx-x64 -property:Configuration=Release

      - name: Create publish folder.
        run:
          mkdir "${{ github.workspace }}/occlusionmacbuild/"

      - name: Copy published .app to a folder.
        run:
          cp -R "${{ github.workspace }}/Occlusion Voice Chat_CrossPlatform/bin/Release/net6.0/osx-x64/publish/Occlusion Voice Chat.app" "${{ github.workspace }}/occlusionmacbuild/"

      - name: Copy Libraries.
        run:
          cp "${{ github.workspace }}/Occlusion Voice Chat_CrossPlatform/maclibs/SDL2.dylib" "${{ github.workspace }}/occlusionmacbuild/Occlusion Voice Chat.app/Contents/MacOS/SDL2.dylib";
          cp "${{ github.workspace }}/Occlusion Voice Chat_CrossPlatform/maclibs/SDL2.a" "${{ github.workspace }}/occlusionmacbuild/Occlusion Voice Chat.app/Contents/MacOS/SDL2.a";
          cp "${{ github.workspace }}/Occlusion Voice Chat_CrossPlatform/maclibs/opus.dylib" "${{ github.workspace }}/occlusionmacbuild/Occlusion Voice Chat.app/Contents/MacOS/opus.dylib"
          
      - name: Zip the published binaries.
        uses: master-atul/tar-action@v1.0.2
        with:
          command: c
          cwd: '${{ github.workspace }}/'
          files: |
            ./occlusionmacbuild
          outPath: occlusion-mac-x64-binaries.tar.gz

      - name: And upload an artifact.
        uses: actions/upload-artifact@v2
        with:
          name: occlusion-mac64-installer-artifact
          path: occlusion-mac-x64-binaries.tar.gz

  build-win:
    # Windows Server 2019
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
    
      - name: Clone in the installer to a folder.
        uses: actions/checkout@v2
        with:
          repository: 'JamDoggie/CrossPlatformInstallerBase'
          path: 'occlusioninstallerclone/'

      - name: Publish Occlusion to a folder.
        run: 
          dotnet publish "${{ github.workspace }}\Occlusion Voice Chat_CrossPlatform\Occlusion Voice Chat_CrossPlatform.csproj" -c "Release Win" -r win-x64 --self-contained true --output "occlusionwinrelease\"

      - name: Publish the auto updater into the published occlusion directory.
        run:
          dotnet publish "${{ github.workspace }}\OcclusionAutoUpdater\OcclusionAutoUpdater.csproj" -c "Release Win" -r win-x64 --self-contained true --output "occlusionwinrelease\"

      #- name: Zip the published binaries.
      #  uses: papeloto/action-zip@v1
      #  with:
      #    files: occlusionwinrelease/
      #    recursive: false
      #    dest: programfiles.zip
      - name: Zip the published binaries.
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'programfiles.zip'
          path: '${{ github.workspace }}\occlusionwinrelease\*'
          
      - name: Copy the published binaries into the installer.
        run:
          copy "${{ github.workspace }}/programfiles.zip" "${{ github.workspace }}/occlusioninstallerclone/CrossPlatformInstallerBase/installerfiles/"
          
      - name: Finally, publish the installer
        run: 
          dotnet publish "${{ github.workspace }}\occlusioninstallerclone\CrossPlatformInstallerBase\CrossPlatformInstallerBase.csproj" -c "Release" -r win-x64 --self-contained true --output "installerpublish\"
          
      - name: Rename the installer.
        run:
          cd "installerpublish/" && ren "CrossPlatformInstallerBase.exe" "occlusion-voice-chat-installer-x64.exe"
          
      - name: Zip up the installer
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'installerartifact.zip'
          path: 'installerpublish/'
        
      - name: And upload an artifact.
        uses: actions/upload-artifact@v2
        with:
          name: occlusion-win64-installer-artifact
          path: installerartifact.zip
          
  build-server-linux:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
    
      - name: Restore libraries
        run: 
          dotnet restore "${{ github.workspace }}\OcclusionDedicatedServer\OcclusionDedicatedServer.csproj" -r linux-x64
          
      - name: Publish server to a folder
        run: 
          dotnet publish "${{ github.workspace }}\OcclusionDedicatedServer\OcclusionDedicatedServer.csproj" -c "Release" -r linux-x64 --self-contained true --output "occlusionlinuxrelease/"

      - name: Zip the published binaries.
        uses: thedoctor0/zip-release@master
        with:
          type: 'tar'
          filename: 'occlusion-linux-portable-server-x64.tar.gz'
          path: '${{ github.workspace }}/occlusionlinuxrelease/'
          
      - name: And upload an artifact.
        uses: actions/upload-artifact@v2
        with:
          name: occlusion-linux-portable-server-x64-artifact
          path: occlusion-linux-portable-server-x64.tar.gz
          
  build-server-win:
    # Windows Server 2019
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Publish server to a folder.
        run: 
          dotnet publish "${{ github.workspace }}\OcclusionDedicatedServer\OcclusionDedicatedServer.csproj" -c "Release Win" -r win-x64 --self-contained true --output "occlusionwinrelease\"
          
      #- name: Zip the published binaries.
      #  uses: papeloto/action-zip@v1
      #  with:
      #    files: occlusionwinrelease/
      #    recursive: false
      #    dest: programfiles.zip
      - name: Zip the published binaries.
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'occlusion-server-win-x64.zip'
          path: '${{ github.workspace }}\occlusionwinrelease\*'
        
      - name: And upload an artifact.
        uses: actions/upload-artifact@v2
        with:
          name: occlusion-server-win-x64-artifact
          path: occlusion-server-win-x64.zip
